### ISSUE TITLE
Set angular as `peerDependency` rather than a regular dependency

### ISSUE THREAD

**Issue by Helveg** [nilsmehlhorn/ngx-operators#25]
The `package.json` can be improved by moving angular to the peer dependencies and specifying the full range of Angular versions that each release is compatible with. This way your users can install `ngx-operators` for whatever Angular version that they are on, rather than having to lock-step each version upgrade.

Here is a doc reference: https://angular.io/guide/creating-libraries#peer-dependencies

**Comment by nilsmehlhorn** [comment]
Hi @Helveg, what's your specific issue here? The Angular dependencies are already correctly listed as peer dependencies for the library project itself: https://github.com/nilsmehlhorn/ngx-operators/blob/1a216d37960caee7a2007bc7cc9c4f80c4c8d27c/projects/ngx-operators/package.json#L24

Note that the project hasn't yet been updated to Angular 15. I'll quote from your PR #26 to try and clear up some confusions:

> I assumed the library is compatible with Angular 15.

The library may be compatible with Angular 15, however, releasing a version for Angular 15 would require going through [Angular's update process](https://angular.io/guide/using-libraries#updating-libraries). This involves the (mostly) automatic update of concrete dependencies of the root ("monorepo") package.json and manual update of peer dependencies of the library's package.json. See the [update to Angular 14](https://github.com/nilsmehlhorn/ngx-operators/commit/c1346806b8788e338167bebbb1dff6833f3e1a24) for example.

> While trying to install from my fork I noticed that the root package.json, the one I modified in this PR, doesn't seem to affect the build artifact. It seems /projects/ngx-operators/(ng-)package.json are the ones being packaged. Maybe we could remove all of the irrelevant conflicting information?

I don't see what irrelevant or conflicting information you're referring to. This project is setup as a regular Angular CLI library project (without a default app). The dependencies in the root package.json are used for building the library, the package.json in the library directory is used for publishing and thus evaluated for compatible peer dependencies when people install the library

**Comment by Helveg** [comment]
Ok, I'll try to go through the motions of what you described here, and see where I end up. But for example the `dependencies` in the root package.json don't seem to be used at all, just the `devDependencies` seem to matter?

**Comment by nilsmehlhorn** [comment]
> I'd like to use this project with Angular 15 :)

Basically, you'll have to revert the changes in your PR and instead follow the steps described on this page: https://update.angular.io/?v=14.0-15.0 (you might need to force the update when there are intermediate incompatabilities between dependencies)

> But for example the dependencies in the root package.json don't seem to be used at all, just the devDependencies seem to matter?

Those dependencies are used for the build step. Please try the following to see what I mean: delete the dependencies inside the root package.json, empty the node_modules directory and run `npm install`. I'll argue you then won't be able to build the project anymore. The difference between dependencies and devDependencies is small in general when dealing with single-page application projects, however, the peerDependencies from the libraries package.json are only _peer_ dependencies meaning they won't be installed when running `npm install`. They're just meant for validating compatibility in a target project where you install this library.

> As an aside, this setup also seems incompatible with directly installing the repository as an npm package, making it difficult to use forks. What is your recommended approach to use forks of this project as npm dependency?

Do you have an example of an Angular library project with a superior structure? The repository is not meant to be installed as an npm package. You can instead run `npm build` and then use [npm link](https://docs.npmjs.com/cli/v9/commands/npm-link) inside `dist/ngx-operators`(that's the directory containing everything published to npm) to install the built package locally into another Angular project.

**Comment by Helveg** [comment]
> Do you have an example of an Angular library project with a superior structure?

My experience has been that when everything is listed in the root `package.json`, that `npm install` can directly run all of the build steps that precede publishing it on npm, and so something like `npm install github:Helveg/ngx-operators` would work to use my fork until some PR is merged and released on the base repo. Not sure if I have immediate examples.

**Comment by nilsmehlhorn** [comment]
> My experience has been that when everything is listed in the root package.json [...]

But everything _is_ listed in the root `package.json`.

> [...] that npm install can directly run all of the build steps that precede publishing it on npm

I don't see how that'd work in practice. It'd probably require a prepare script but even then I guess the file paths won't add up. I advise you to use npm link instead.

**Comment by Helveg** [comment]
> But everything is listed in the root package.json.

If it were, `npm install github:...` would read `package.json` and run the entire build process, like all node packages do, and like anything that can bundle itself with an `npm run` script can do. Is there a link configured between the root `package.json` and the `ngx-operators/package.json` that npm is supposed to understand? None of the `scripts` in `package.json` seem to refer to anything `ngx-operators` related but that may be because of my limited understanding of this project's layout.

Is something like this maybe missing: https://docs.npmjs.com/cli/v9/using-npm/scripts#prepare-and-prepublish?

**Comment by Helveg** [comment]
@nilsmehlhorn, I've tried again, but I still don't understand what these dependencies are for:

```
  "dependencies": {
    "@angular/animations": "^14.1.1",
    "@angular/common": "^14.1.1",
    "@angular/compiler": "^14.1.1",
    "@angular/core": "^14.1.1",
    "@angular/forms": "^14.1.1",
    "@angular/platform-browser": "^14.1.1",
    "@angular/platform-browser-dynamic": "^14.1.1",
    "@angular/router": "^14.1.1",
    "rxjs": "^6.5.5",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.4"
  },
```

1. Are they dependencies of `ngx-operators`? If so, why aren't they in the deeper `package.json` together with the `peerDependencies`?
2. When I do `ng update`, they're all migrated to v15, while I'd like to keep them in the same permissive 14-15 range like the peer dependencies. Or 6.5.5-8 for rxjs for example.
