### ISSUE TITLE
Angular 10 Peer Dependency

### ISSUE THREAD

**Issue by mlewe** [nilsmehlhorn/ngx-operators#8]
According to #5, this has been updated for Angular 10.

However the actual `package.json` still declares a peer dependency for Angular 9.
https://github.com/nilsmehlhorn/ngx-operators/blob/ce21510e2aef88c990171dc6abfc3dc163cf4d24/projects/ngx-operators/package.json#L24

I think you might have forgotten to change it.

**Comment by nilsmehlhorn** [comment]
Yes, you're right. Other than that the library is already compatible with Angular, you might just get a warning during installation.

**Comment by mfluehr** [comment]
Any updates on this? I'd like to update my project's Angular version.

**Comment by nilsmehlhorn** [comment]
I'll update the library on the weekend.
